version: '3.8'

services:
  reactfrontend:
    image: reactportfolio:latest
    ports:
      - "3000:80"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
    restart: always
